-- ─────────────────────────────────────────────────────────────
-- Pop-Pin 02: 프로필 · 커플 연결 · 프로필 사진 저장소
-- Supabase 대시보드 → SQL Editor → 이 파일 전체를 붙여 넣고 Run 하세요.
-- 여러 번 실행해도 안전하도록(if not exists / drop if exists) 작성했습니다.
-- ─────────────────────────────────────────────────────────────


-- ═════════ 1. profiles: 사용자 프로필 ═════════
-- auth.users(Supabase가 관리하는 로그인 계정)와 1:1로 연결되는 '우리 앱용' 사용자 정보입니다.
-- auth.users는 직접 수정할 수 없으므로, 닉네임·사진처럼 바꿀 수 있는 정보는 여기에 따로 둡니다.
create table if not exists public.profiles (
    -- 계정이 삭제되면(on delete cascade) 프로필도 자동으로 함께 삭제됩니다.
    id uuid primary key references auth.users(id) on delete cascade,
    nickname text not null default '사용자'
        check (char_length(nickname) between 1 and 20),   -- 닉네임은 1~20자
    avatar_url text,
    invite_code text not null unique,                     -- 커플 연결용 6자리 초대 코드
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- 헷갈리는 글자(0/O, 1/I/L)를 뺀 6자리 초대 코드를 만듭니다. 이미 있는 코드면 다시 뽑습니다.
create or replace function public.generate_invite_code()
returns text
language plpgsql
set search_path = ''
as $$
declare
    chars constant text := 'ABCDEFGHJKMNPQRSTUVWXYZ23456789';
    code text;
begin
    loop
        code := '';
        for i in 1..6 loop
            code := code || substr(chars, 1 + floor(random() * length(chars))::int, 1);
        end loop;
        exit when not exists (select 1 from public.profiles where invite_code = code);
    end loop;
    return code;
end;
$$;

-- 새 사용자가 처음 로그인(가입)하면 자동으로 프로필을 만들어 주는 함수입니다.
-- 카카오가 넘겨준 닉네임·프로필 사진(raw_user_meta_data)을 초기값으로 사용합니다.
-- security definer: 이 함수는 '만든 사람(관리자)' 권한으로 실행되어, 일반 사용자는 못 하는 insert를 할 수 있습니다.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''   -- 보안: 다른 스키마의 같은 이름 함수가 끼어들지 못하게 고정
as $$
begin
    insert into public.profiles (id, nickname, avatar_url, invite_code)
    values (
        new.id,
        left(coalesce(
            nullif(new.raw_user_meta_data ->> 'full_name', ''),
            nullif(new.raw_user_meta_data ->> 'name', ''),
            '사용자'
        ), 20),
        coalesce(new.raw_user_meta_data ->> 'avatar_url', new.raw_user_meta_data ->> 'picture'),
        public.generate_invite_code()
    )
    on conflict (id) do nothing;
    return new;
end;
$$;

-- 트리거: auth.users에 새 행이 생길 때마다 위 함수를 자동 실행합니다.
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
    after insert on auth.users
    for each row execute function public.handle_new_user();

-- 이미 가입한 사용자(지금 테스트로 로그인한 계정 등)는 트리거가 없던 시절이라 프로필이 없습니다. 채워 줍니다.
insert into public.profiles (id, nickname, avatar_url, invite_code)
select
    u.id,
    left(coalesce(
        nullif(u.raw_user_meta_data ->> 'full_name', ''),
        nullif(u.raw_user_meta_data ->> 'name', ''),
        '사용자'
    ), 20),
    coalesce(u.raw_user_meta_data ->> 'avatar_url', u.raw_user_meta_data ->> 'picture'),
    public.generate_invite_code()
from auth.users as u
where not exists (select 1 from public.profiles as p where p.id = u.id);

-- 프로필을 수정하면 updated_at을 현재 시각으로 자동 갱신합니다.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
    new.updated_at := now();
    return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
    before update on public.profiles
    for each row execute function public.set_updated_at();


-- ═════════ 2. couples / couple_members: 커플 연결 ═════════
-- couples: 커플 1쌍 = 1행 (연결된 날짜 보관)
create table if not exists public.couples (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now()
);

-- couple_members: 커플에 속한 사람 (커플 1쌍 = 2행)
-- user_id가 primary key → 한 사람은 '동시에 한 커플에만' 속할 수 있다는 규칙을 DB가 강제합니다.
create table if not exists public.couple_members (
    user_id uuid primary key references public.profiles(id) on delete cascade,
    couple_id bigint not null references public.couples(id) on delete cascade,
    joined_at timestamptz not null default now()
);

create index if not exists couple_members_couple_id_idx on public.couple_members(couple_id);

-- 현재 로그인한 사람의 커플 id를 돌려주는 도우미 함수 (보안 규칙에서 사용)
-- security definer로 만들어야 보안 규칙 안에서 같은 테이블을 다시 조회할 때 무한 반복(재귀)이 생기지 않습니다.
create or replace function public.my_couple_id()
returns bigint
language sql
stable
security definer
set search_path = ''
as $$
    select couple_id from public.couple_members where user_id = auth.uid();
$$;

-- 초대 코드로 커플을 연결하는 함수 (프론트에서 supabase.rpc('connect_couple')로 호출)
-- 테이블에 직접 insert를 허용하지 않고 이 함수만 열어 두면, 검사를 건너뛴 조작 요청을 막을 수 있습니다.
create or replace function public.connect_couple(partner_code text)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
    me uuid := auth.uid();
    partner uuid;
    new_couple_id bigint;
begin
    if me is null then
        raise exception '로그인이 필요해요.';
    end if;

    -- 대소문자·앞뒤 공백을 정리해서 코드 주인을 찾습니다.
    select id into partner
    from public.profiles
    where invite_code = upper(trim(partner_code));

    if partner is null then
        raise exception '초대 코드를 찾을 수 없어요.';
    end if;
    if partner = me then
        raise exception '내 초대 코드는 입력할 수 없어요.';
    end if;
    if exists (select 1 from public.couple_members where user_id = me) then
        raise exception '이미 커플로 연결되어 있어요.';
    end if;
    if exists (select 1 from public.couple_members where user_id = partner) then
        raise exception '상대방이 이미 다른 사람과 연결되어 있어요.';
    end if;

    insert into public.couples default values returning id into new_couple_id;
    insert into public.couple_members (user_id, couple_id)
    values (me, new_couple_id), (partner, new_couple_id);

    return new_couple_id;
exception
    -- 두 사람이 거의 동시에 연결을 시도해 primary key가 겹치는 경우
    when unique_violation then
        raise exception '이미 연결된 사용자가 있어요. 다시 시도해 주세요.';
end;
$$;

-- 커플 연결 해제 함수: 내 커플 행을 지우면 couple_members도 cascade로 함께 지워집니다.
create or replace function public.disconnect_couple()
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
    my_couple bigint;
begin
    select couple_id into my_couple from public.couple_members where user_id = auth.uid();
    if my_couple is null then
        raise exception '연결된 커플이 없어요.';
    end if;
    delete from public.couples where id = my_couple;
end;
$$;


-- ═════════ 3. RLS(행 수준 보안) 규칙 ═════════
-- anon 키는 브라우저에 공개되는 키입니다. RLS를 켜야 "누가 어떤 행을 읽고 쓸 수 있는지"를 DB가 직접 검사합니다.
-- RLS를 켜고 정책(policy)이 없으면 기본값은 '모두 거부'입니다.
alter table public.profiles enable row level security;
alter table public.couples enable row level security;
alter table public.couple_members enable row level security;

-- profiles: 내 프로필 + 내 연인의 프로필만 조회 가능
drop policy if exists "profiles_select_self_and_partner" on public.profiles;
create policy "profiles_select_self_and_partner" on public.profiles
    for select to authenticated
    using (
        id = (select auth.uid())
        or id in (
            select cm.user_id from public.couple_members as cm
            where cm.couple_id = public.my_couple_id()
        )
    );

-- profiles: 내 프로필만 수정 가능
drop policy if exists "profiles_update_self" on public.profiles;
create policy "profiles_update_self" on public.profiles
    for update to authenticated
    using (id = (select auth.uid()))
    with check (id = (select auth.uid()));

-- 추가 방어: 프로필에서 수정 가능한 칸은 닉네임·사진뿐입니다. (초대 코드 등을 바꾸지 못하게)
revoke update on public.profiles from anon, authenticated;
grant update (nickname, avatar_url) on public.profiles to authenticated;
-- insert/delete는 트리거와 함수만 하도록 일반 사용자 권한을 뺍니다.
revoke insert, delete on public.profiles, public.couples, public.couple_members from anon, authenticated;
revoke update on public.couples, public.couple_members from anon, authenticated;

-- couples / couple_members: 내 커플 정보만 조회 가능 (수정은 위 함수로만)
drop policy if exists "couples_select_mine" on public.couples;
create policy "couples_select_mine" on public.couples
    for select to authenticated
    using (id = public.my_couple_id());

drop policy if exists "couple_members_select_mine" on public.couple_members;
create policy "couple_members_select_mine" on public.couple_members
    for select to authenticated
    using (couple_id = public.my_couple_id());

-- 함수 실행 권한: 기본값은 '누구나(public)'라서, 로그인한 사용자만 쓰도록 좁힙니다.
revoke execute on function public.connect_couple(text), public.disconnect_couple(), public.my_couple_id() from public, anon;
grant execute on function public.connect_couple(text), public.disconnect_couple(), public.my_couple_id() to authenticated;
-- 내부용 함수는 아무도 직접 호출하지 못하게 막습니다. (트리거는 관리자 권한으로 알아서 실행됨)
revoke execute on function public.handle_new_user(), public.generate_invite_code() from public, anon, authenticated;


-- ═════════ 4. Storage: 프로필 사진 버킷 ═════════
-- avatars 버킷: 누구나 사진을 '볼' 수 있는(public) 공간. 2MB 이하 이미지만 허용합니다.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('avatars', 'avatars', true, 2097152, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do nothing;

-- 업로드/삭제는 '자기 폴더'(avatars/내-사용자-id/...)에서만 가능합니다.
-- storage.foldername(name)[1] = 파일 경로의 첫 번째 폴더 이름
drop policy if exists "avatars_insert_own_folder" on storage.objects;
create policy "avatars_insert_own_folder" on storage.objects
    for insert to authenticated
    with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = (select auth.uid())::text);

drop policy if exists "avatars_select_own_folder" on storage.objects;
create policy "avatars_select_own_folder" on storage.objects
    for select to authenticated
    using (bucket_id = 'avatars' and (storage.foldername(name))[1] = (select auth.uid())::text);

drop policy if exists "avatars_delete_own_folder" on storage.objects;
create policy "avatars_delete_own_folder" on storage.objects
    for delete to authenticated
    using (bucket_id = 'avatars' and (storage.foldername(name))[1] = (select auth.uid())::text);
