-- ─────────────────────────────────────────────────────────────
-- Pop-Pin 04: 커플 연결을 "요청 → 수락" 방식으로 변경
-- Supabase 대시보드 → SQL Editor → 이 파일 전체를 붙여 넣고 Run 하세요.
-- 여러 번 실행해도 안전하도록(if not exists / create or replace / drop if exists) 작성했습니다.
--
-- 바뀌는 흐름:
--   (전) 코드 입력 → 즉시 커플 성립
--   (후) 코드 입력 → 요청 보냄 → 상대가 수락하면 커플 성립 / 거절·취소하면 요청 삭제
--   ※ 두 사람이 서로에게 요청을 보내면(= 둘 다 동의) 바로 연결됩니다.
-- ─────────────────────────────────────────────────────────────


-- ═════════ 1. couple_requests: 대기 중인 커플 요청 ═════════
-- 요청 1건 = 1행. 수락·거절·취소되면 행을 지웁니다. (남아 있는 행 = 아직 대기 중인 요청)
create table if not exists public.couple_requests (
    id bigint generated by default as identity primary key,
    -- 보낸 사람. unique → 한 사람은 '한 번에 1개'의 요청만 보낼 수 있다는 규칙을 DB가 강제합니다.
    sender_id uuid not null unique references public.profiles(id) on delete cascade,
    -- 받는 사람. 여러 사람에게서 요청을 받을 수는 있습니다. (잘못 온 요청은 거절하면 됨)
    receiver_id uuid not null references public.profiles(id) on delete cascade,
    created_at timestamptz not null default now(),
    -- 나 자신에게 요청하는 것을 DB 수준에서 막습니다.
    constraint couple_requests_not_self check (sender_id <> receiver_id)
);

-- "나에게 온 요청" 조회를 빠르게 하기 위한 색인 (sender_id는 unique라서 자동으로 색인이 있음)
create index if not exists couple_requests_receiver_id_idx on public.couple_requests(receiver_id);


-- ═════════ 2. 내부용 도우미: 두 사람을 커플로 만들기 ═════════
-- 수락할 때와 '서로 요청'일 때 둘 다 같은 일을 하므로 한 곳에 모았습니다.
-- 커플을 만든 뒤, 두 사람과 관련된 대기 요청(보낸 것·받은 것)을 모두 정리합니다.
-- 사용자가 직접 부르지 못하게 아래에서 실행 권한을 모두 막습니다. (다른 함수 안에서만 사용)
create or replace function public.create_couple_internal(user_a uuid, user_b uuid)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
    new_couple_id bigint;
begin
    if exists (select 1 from public.couple_members where user_id = user_a) then
        raise exception '이미 커플로 연결되어 있어요.';
    end if;
    if exists (select 1 from public.couple_members where user_id = user_b) then
        raise exception '상대방이 이미 다른 사람과 연결되어 있어요.';
    end if;

    insert into public.couples default values returning id into new_couple_id;
    insert into public.couple_members (user_id, couple_id)
    values (user_a, new_couple_id), (user_b, new_couple_id);

    -- 이제 두 사람 모두 커플이 됐으니, 두 사람이 주고받던 다른 요청은 의미가 없어 지웁니다.
    delete from public.couple_requests
    where sender_id in (user_a, user_b)
       or receiver_id in (user_a, user_b);

    return new_couple_id;
exception
    -- 거의 동시에 다른 연결이 성립해 couple_members 기본키가 겹친 경우
    when unique_violation then
        raise exception '이미 연결된 사용자가 있어요. 다시 시도해 주세요.';
end;
$$;


-- ═════════ 3. 요청 보내기: send_couple_request(초대 코드) ═════════
-- 돌려주는 값: 'sent' = 요청을 보냄 / 'connected' = 상대도 나에게 요청해 둔 상태라 바로 연결됨
create or replace function public.send_couple_request(partner_code text)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
    me uuid := auth.uid();
    partner uuid;
    my_pending_receiver uuid;
begin
    if me is null then
        raise exception '로그인이 필요해요.';
    end if;

    -- 대소문자·앞뒤 공백을 정리해서 코드 주인을 찾습니다.
    select id into partner
    from public.profiles
    where invite_code = upper(trim(partner_code));

    if partner is null then
        raise exception '초대 코드를 찾을 수 없어요.';
    end if;
    if partner = me then
        raise exception '내 초대 코드는 입력할 수 없어요.';
    end if;
    if exists (select 1 from public.couple_members where user_id = me) then
        raise exception '이미 커플로 연결되어 있어요.';
    end if;
    if exists (select 1 from public.couple_members where user_id = partner) then
        raise exception '상대방이 이미 다른 사람과 연결되어 있어요.';
    end if;

    -- 상대가 이미 나에게 요청을 보내 둔 상태 → 둘 다 동의한 것이므로 바로 연결합니다.
    if exists (
        select 1 from public.couple_requests
        where sender_id = partner and receiver_id = me
    ) then
        perform public.create_couple_internal(me, partner);
        return 'connected';
    end if;

    -- 내가 이미 보낸 요청이 있는지 확인합니다. (한 번에 1개만 가능)
    select receiver_id into my_pending_receiver
    from public.couple_requests
    where sender_id = me;

    if my_pending_receiver = partner then
        raise exception '이미 요청을 보냈어요. 상대가 수락할 때까지 기다려 주세요.';
    end if;
    if my_pending_receiver is not null then
        raise exception '이미 보낸 요청이 있어요. 취소한 뒤 다시 보내 주세요.';
    end if;

    insert into public.couple_requests (sender_id, receiver_id) values (me, partner);
    return 'sent';
exception
    -- 거의 동시에 두 번 눌러 sender_id unique가 겹친 경우
    when unique_violation then
        raise exception '이미 보낸 요청이 있어요.';
end;
$$;


-- ═════════ 4. 받은 요청 수락: accept_couple_request(요청 id) ═════════
create or replace function public.accept_couple_request(request_id bigint)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
    me uuid := auth.uid();
    requester uuid;
begin
    if me is null then
        raise exception '로그인이 필요해요.';
    end if;

    -- '나에게 온' 요청인지 확인합니다. 남의 요청 id를 넣어도 찾지 못합니다.
    select sender_id into requester
    from public.couple_requests
    where id = request_id and receiver_id = me;

    if requester is null then
        raise exception '요청을 찾을 수 없어요. 상대가 요청을 취소했을 수 있어요.';
    end if;

    return public.create_couple_internal(me, requester);
end;
$$;


-- ═════════ 5. 받은 요청 거절: reject_couple_request(요청 id) ═════════
-- 정책: 거절하면 요청이 조용히 사라집니다. (보낸 사람에게 따로 알리지 않음)
create or replace function public.reject_couple_request(request_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
    if auth.uid() is null then
        raise exception '로그인이 필요해요.';
    end if;

    delete from public.couple_requests
    where id = request_id and receiver_id = auth.uid();

    -- found: 바로 앞 SQL이 행을 1개 이상 처리했는지 알려주는 값
    if not found then
        raise exception '요청을 찾을 수 없어요. 이미 처리되었을 수 있어요.';
    end if;
end;
$$;


-- ═════════ 6. 보낸 요청 취소: cancel_couple_request() ═════════
-- 보낸 요청은 1개뿐이라 id 없이 '내가 보낸 요청'을 지웁니다.
create or replace function public.cancel_couple_request()
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
    if auth.uid() is null then
        raise exception '로그인이 필요해요.';
    end if;

    delete from public.couple_requests where sender_id = auth.uid();

    if not found then
        raise exception '취소할 요청이 없어요. 이미 수락되었거나 거절되었을 수 있어요.';
    end if;
end;
$$;


-- ═════════ 7. RLS(행 수준 보안) 규칙 ═════════
alter table public.couple_requests enable row level security;

-- couple_requests: 내가 보냈거나 내가 받은 요청만 조회 가능
drop policy if exists "couple_requests_select_mine" on public.couple_requests;
create policy "couple_requests_select_mine" on public.couple_requests
    for select to authenticated
    using (
        sender_id = (select auth.uid())
        or receiver_id = (select auth.uid())
    );

-- 테이블에 직접 쓰기는 모두 막고, 검사가 들어 있는 위 함수들로만 바꿀 수 있게 합니다.
revoke insert, update, delete on public.couple_requests from anon, authenticated;

-- profiles: 요청을 주고받는 상대의 프로필도 볼 수 있게 추가 허용
-- (받은 요청에 "○○님이 커플 요청을 보냈어요"처럼 닉네임·사진을 보여주기 위해)
-- 기존 정책(나 + 연인)과 합쳐져서 "나 + 연인 + 요청 상대"가 조회됩니다. (정책끼리는 OR로 합쳐짐)
-- couple_requests의 정책은 profiles를 다시 조회하지 않으므로 무한 재귀가 생기지 않습니다.
drop policy if exists "profiles_select_request_parties" on public.profiles;
create policy "profiles_select_request_parties" on public.profiles
    for select to authenticated
    using (
        id in (
            select cr.sender_id from public.couple_requests as cr
            where cr.receiver_id = (select auth.uid())
            union
            select cr.receiver_id from public.couple_requests as cr
            where cr.sender_id = (select auth.uid())
        )
    );


-- ═════════ 8. 함수 실행 권한 ═════════
-- 새 함수: 로그인한 사용자만 호출 가능
revoke execute on function
    public.send_couple_request(text),
    public.accept_couple_request(bigint),
    public.reject_couple_request(bigint),
    public.cancel_couple_request()
from public, anon;
grant execute on function
    public.send_couple_request(text),
    public.accept_couple_request(bigint),
    public.reject_couple_request(bigint),
    public.cancel_couple_request()
to authenticated;

-- 내부용 도우미는 아무도 직접 호출하지 못하게 막습니다. (위 함수들 안에서만 사용)
revoke execute on function public.create_couple_internal(uuid, uuid) from public, anon, authenticated;

-- 예전 '즉시 연결' 함수는 더 이상 쓰지 않습니다.
-- 호출 권한을 막아 두지 않으면, 누군가 직접 호출해서 수락 단계를 건너뛸 수 있습니다.
-- ⚠️ 02_profiles_couples.sql을 다시 실행하면 이 권한이 되살아나므로, 02를 재실행했다면 이 파일도 다시 실행하세요.
revoke execute on function public.connect_couple(text) from public, anon, authenticated;
