-- Pop-Course 초기 데이터베이스 스키마
-- Supabase SQL Editor에서 파일 전체를 실행하면 테이블과 샘플 데이터가 생성됩니다.

-- 장소 정보를 저장하는 테이블입니다.
create table if not exists public.places (
    id bigint generated by default as identity primary key,
    name text not null,
    category text not null,
    lat double precision not null,
    lng double precision not null,
    address text not null,
    start_date date,
    end_date date,
    tags text[] not null default '{}',
    image_url text,
    created_at timestamptz not null default now()
);

-- 장소별 리뷰 링크를 저장하는 테이블입니다.
create table if not exists public.reviews (
    id bigint generated by default as identity primary key,
    place_id bigint not null references public.places(id) on delete cascade,
    title text not null,
    link text not null,
    snippet text,
    published_date date,
    created_at timestamptz not null default now()
);

-- 지도 필터링과 리뷰 조회가 잦으므로 검색용 인덱스를 추가합니다.
create index if not exists places_category_idx on public.places(category);
create index if not exists reviews_place_id_idx on public.reviews(place_id);

-- 개발 초기에 화면과 API를 확인할 수 있도록 테스트 장소를 입력합니다.
-- 기존 초기 샘플을 제거해 행궁동 중심 데이터만 남깁니다.
delete from public.places
where name in (
    '성수 팝업 스튜디오',
    '홍대 거리 예술 축제',
    '서울숲 브런치 핫플',
    '버터스카이'
);

insert into public.places
    (name, category, lat, lng, address, start_date, end_date, tags, image_url)
select *
from (
    values
        (
            '버건디 행궁'::text,
            'restaurant'::text,
            37.2866350::double precision,
            127.0130833::double precision,
            '경기 수원시 팔달구 신풍로63번길 11-3 1층'::text,
            null::date,
            null::date,
            array['행궁동', '양식', '데이트', '주차 불가', '공영주차장 이용']::text[],
            null::text
        ),
        (
            '2026 정조대왕 능행차'::text,
            'festival'::text,
            37.2818419::double precision,
            127.0137108::double precision,
            '경기 수원시 팔달구 정조로 825 화성행궁 일대'::text,
            null::date,
            null::date,
            array['행궁동', '전통문화', '퍼레이드', '접근성', '주차 혼잡 예상']::text[],
            null::text
        ),
        (
            '설빙 수원행리단길행궁점'::text,
            'cafe'::text,
            37.2854881::double precision,
            127.0140943::double precision,
            '경기 수원시 팔달구 신풍로 48-12 3층'::text,
            null::date,
            null::date,
            array['행궁동', '행리단길', '디저트카페', '주차 가능', '접근성']::text[],
            null::text
        )
) as sample(name, category, lat, lng, address, start_date, end_date, tags, image_url)
where not exists (
    select 1
    from public.places as existing
    where existing.name = sample.name
      and existing.category = sample.category
);

-- 첫 번째 장소에 연결되는 테스트 리뷰를 입력합니다.
insert into public.reviews
    (place_id, title, link, snippet, published_date)
select
    place.id,
    '버건디 행궁 방문 후기',
    'https://place.map.kakao.com/1789547584',
    '행궁동 데이트에 어울리는 분위기 좋은 양식 맛집입니다.',
    null
from public.places as place
where place.name = '버건디 행궁'
  and not exists (
      select 1
      from public.reviews as review
      where review.link = 'https://place.map.kakao.com/1789547584'
  );