-- Pop-Course 초기 데이터베이스 스키마
-- Supabase SQL Editor에서 파일 전체를 실행하면 테이블과 샘플 데이터가 생성됩니다.

-- 장소 정보를 저장하는 테이블입니다.
create table if not exists public.places (
    id bigint generated by default as identity primary key,
    name text not null,
    category text not null,
    lat double precision not null,
    lng double precision not null,
    address text not null,
    start_date date,
    end_date date,
    tags text[] not null default '{}',
    image_url text,
    created_at timestamptz not null default now()
);

-- 장소별 리뷰 링크를 저장하는 테이블입니다.
create table if not exists public.reviews (
    id bigint generated by default as identity primary key,
    place_id bigint not null references public.places(id) on delete cascade,
    title text not null,
    link text not null,
    snippet text,
    published_date date,
    created_at timestamptz not null default now()
);

-- 지도 필터링과 리뷰 조회가 잦으므로 검색용 인덱스를 추가합니다.
create index if not exists places_category_idx on public.places(category);
create index if not exists reviews_place_id_idx on public.reviews(place_id);

-- 개발 초기에 화면과 API를 확인할 수 있도록 테스트 장소를 입력합니다.
insert into public.places
    (name, category, lat, lng, address, start_date, end_date, tags, image_url)
select *
from (
    values
        (
            '성수 팝업 스튜디오'::text,
            'popup'::text,
            37.5446::double precision,
            127.0561::double precision,
            '서울특별시 성동구 성수이로 24길'::text,
            '2026-09-01'::date,
            '2026-10-15'::date,
            array['실내', '성수', '사진']::text[],
            null::text
        ),
        (
            '홍대 거리 예술 축제'::text,
            'festival'::text,
            37.5563::double precision,
            126.9236::double precision,
            '서울특별시 마포구 홍익로 일대'::text,
            '2026-10-03'::date,
            '2026-10-05'::date,
            array['야외', '홍대', '공연']::text[],
            null::text
        ),
        (
            '서울숲 브런치 핫플'::text,
            'hotplace'::text,
            37.5445::double precision,
            127.0374::double precision,
            '서울특별시 성동구 서울숲2길'::text,
            null::date,
            null::date,
            array['성수', '브런치', '데이트']::text[],
            null::text
        )
) as sample(name, category, lat, lng, address, start_date, end_date, tags, image_url)
where not exists (
    select 1
    from public.places as existing
    where existing.name = sample.name
      and existing.category = sample.category
);

-- 첫 번째 장소에 연결되는 테스트 리뷰를 입력합니다.
insert into public.reviews
    (place_id, title, link, snippet, published_date)
select
    place.id,
    '성수 팝업 스튜디오 방문 후기',
    'https://example.com/reviews/seongsu-popup',
    '공간 구성과 체험 동선이 좋았던 팝업스토어 후기입니다.',
    '2026-09-10'
from public.places as place
where place.name = '성수 팝업 스튜디오'
  and not exists (
      select 1
      from public.reviews as review
      where review.link = 'https://example.com/reviews/seongsu-popup'
  );